name: Testing

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install packages
      run: |
        sudo apt-get install -y unbound net-tools
        sudo python3 -m pip install pyyaml
        sudo python3 -m pip install --upgrade dnspython
        sudo systemctl stop unbound
    - id: unbound_version
      run: echo "##[set-output name=data;]$(unbound -V | sed -n 's/^[V|v]ersion //p')"
    - id: python_version
      run: echo "##[set-output name=data;]$(python3 --version | sed -n 's/^[P|y]ython //p')"
    - name: Unbound badge
      uses: RubbaBoy/BYOB@v1.1.0
      with:
        NAME: unbound
        LABEL: 'Unbound'
        STATUS: ${{ steps.unbound_version.outputs.data }}
        COLOR: 027CB9
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Python badge
      uses: RubbaBoy/BYOB@v1.1.0
      with:
        NAME: python
        LABEL: 'Python'
        STATUS: ${{ steps.python_version.outputs.data }}
        COLOR: 027CB9
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Reconfigure unbound to enable remote control
      run: |
        sudo cp -rf tests/unbound_remotecontrol.conf /etc/unbound/unbound.conf.d/
        sudo systemctl start unbound
        sudo systemctl status unbound
        sudo netstat -anp | grep unbound
        sudo unbound-control status
    - name: Run Python tests
      run: |
        sudo python3 -m unittest tests.test_connect
    - name: Reconfigure unbound with TLS
      run: |
        sudo systemctl stop unbound
        sudo rm -rf /etc/unbound/unbound.conf.d/unbound_remotecontrol.conf
        sudo cp -rf tests/unbound_remotecontrol_tls.conf /etc/unbound/unbound.conf.d/
        sudo unbound-control-setup
        sudo systemctl start unbound
        sudo systemctl status unbound
        sudo netstat -anp | grep unbound
        sudo unbound-control status
    - name: Run Python tests in TLS mode
      run: |
        sudo python3 -m unittest tests.test_tls_connect
    - name: Run Python other tests
      run: |
        sudo python3 -m unittest tests.test_zone