name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unbound-e2e:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        unbound: [ '1.12.0' , '1.13.2', '1.14.0', '1.15.0'  ] #
        python: [ '3.8', '3.9', '3.10'  ] # 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install python requirements
      run: |
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m pip install --upgrade dnspython

    - name: Deploy unbound with TCP remote control 
      run: |
        sudo docker run --name unbound01 --health-cmd='drill @127.0.0.1 -p 5300 github.com  || exit 1' --health-interval=2s -d --net=host -v $(pwd)/testsdata/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro mvance/unbound:${{ matrix.unbound }}
        while true; do status=$(sudo docker inspect --format='{{.State.Health.Status}}' unbound01); if [ $status == "healthy" ]; then break; else sleep 1; fi; done

    - run: sudo docker logs unbound01
      if: always()

    - name: Run Python tests for tcp
      run: |
        sudo python3 -m unittest tests.test_connect

    - name: Restart unbound with TLS remote control 
      run: |
        sudo docker exec unbound01 /opt/unbound/sbin/unbound-control-setup
        sudo docker cp unbound01:/opt/unbound/etc/unbound/unbound_control.pem /tmp/unbound_control.pem
        sudo docker cp unbound01:/opt/unbound/etc/unbound/unbound_control.key /tmp/unbound_control.key
        sudo docker cp unbound01:/opt/unbound/etc/unbound/unbound_server.pem /tmp/unbound_server.pem
        sudo docker stop unbound01
        sudo cp -rf $(pwd)/testsdata/unbound_tls.conf $(pwd)/testsdata/unbound.conf
        sudo docker start unbound01
        while true; do status=$(sudo docker inspect --format='{{.State.Health.Status}}' unbound01); if [ $status == "healthy" ]; then break; else sleep 1; fi; done

    - name: Run Python tests for tls
      run: |
        sudo python3 -m unittest tests.test_tls_connect
        sudo python3 -m unittest tests.test_zone

    - name: Deploy unbound with UNIX remote control
      run: |
        sudo mkdir /tmp/unbound
        sudo chown -R 1000:1000 /tmp/unbound/
        sudo docker run --name unbound02 --health-cmd='drill @127.0.0.1 -p 5300 github.com  || exit 1' --health-interval=2s -d --net=host -v /tmp/unbound/:/tmp/unbound/ -v $(pwd)/testsdata/unbound_unix.conf:/opt/unbound/etc/unbound/unbound.conf:ro mvance/unbound:${{ matrix.unbound }}
        while true; do status=$(sudo docker inspect --format='{{.State.Health.Status}}' unbound02); if [ $status == "healthy" ]; then break; else sleep 1; fi; done

    - name: Run Python tests for unix socket
      run: |
        sudo python3 -m unittest tests.test_unix_connect
