name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unbound:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run --name unbound -d --net=host -v $(pwd)/testsdata/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro mvance/unbound:1.13.2

    - name: Run Python tests 
      run: |
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m unittest tests.test_connect