name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install packages
      run: |
        sudo apt-get install -y unbound net-tools
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m pip install --upgrade dnspython
        sudo systemctl stop unbound

    - name: Reconfigure unbound to enable remote control
      run: |
        sudo cp -rf tests/unbound_remotecontrol.conf /etc/unbound/unbound.conf.d/
        sudo systemctl start unbound
        sudo systemctl status unbound
        sudo netstat -anp | grep unbound
        sudo unbound-control status

    - name: Run Python tests
      run: |
        sudo python3 -m unittest tests.test_connect

    - name: Reconfigure unbound with TLS
      run: |
        sudo systemctl stop unbound
        sudo rm -rf /etc/unbound/unbound.conf.d/unbound_remotecontrol.conf
        sudo cp -rf tests/unbound_remotecontrol_tls.conf /etc/unbound/unbound.conf.d/
        sudo unbound-control-setup
        sudo systemctl start unbound
        sudo systemctl status unbound
        sudo netstat -anp | grep unbound
        sudo unbound-control status

    - name: Run Python tests in TLS mode
      run: |
        sudo python3 -m unittest tests.test_tls_connect
        
    - name: Run Python other tests
      run: |
        sudo python3 -m unittest tests.test_zone