name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unbound:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        unbound: [ '1.12.0', '1.13.2' ]
        python: [ '3.8', '3.9' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Deploy unbound with insecure remote control 
      run: |
        sudo docker run --name unbound01 -d --net=host -v $(pwd)/testsdata/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro mvance/unbound:${{ matrix.unbound }}

    - name: Deploy unbound with secure remote control 
      run: |
        sudo docker run --name unbound02 -d --net=host -v $(pwd)/testsdata/unbound_tls.conf:/opt/unbound/etc/unbound/unbound.conf:ro mvance/unbound:${{ matrix.unbound }}
        sudo docker exec unbound02  /opt/unbound/sbin/unbound-control-setup
        sudo docker cp unbound02:/opt/unbound/etc/unbound/unbound_control.pem /tmp/unbound_control.pem
        sudo docker cp unbound02:/opt/unbound/etc/unbound/unbound_control.key /tmp/unbound_control.key
        sudo docker cp unbound02:/opt/unbound/etc/unbound/unbound_server.pem /tmp/unbound_server.pem

    - name: Run Python tests 
      run: |
        sudo python3 -m pip install -r requirements.txt
        sudo python3 -m unittest tests.test_connect
        sudo python3 -m unittest tests.test_tls_connect
        sudo python3 -m unittest tests.test_zone